services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: example
      RUSTFS_SECRET_KEY: password
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
      RUSTFS_VOLUMES: /data
    volumes:
      - ./data:/data
