FROM alpine:latest

# Install required packages and MinIO client in a single layer
RUN apk add --no-cache curl findutils bash && \
    curl -L https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc && \
    chmod +x /usr/local/bin/mc

# Set working directory
WORKDIR /app

# Default command (will be overridden in docker-compose)
CMD ["sh"]